in_struct = False
in_enum = False

def check_pattern(line: str) -> str:
    global in_struct
    global in_enum
    if in_struct:
        if line.startswith(r"}"):
            in_struct = False
        return line[:line.find(";") + 1]
    elif in_enum:
        if line.startswith(r"}"):
            in_struct = False
            return line[:line.find(";") + 1]
        elif line.find(",") != -1:
            return line[:line.find(",") + 1]
        else:
            return line[:line.find(",") + 1]
    if line.startswith("typedef"):
        if line.split(" ")[1] == "struct" \
        and line.find(r"{") != -1:
            in_struct = True
            return line[:line.find(r"{") + 1]
        elif line.split(" ")[1] == "enum":
            in_enum = True
            return line[:line.find(r"{") + 1]
        return line[:line.find(";") + 1]
    elif line.startswith("RLAPI"):
        return line[:line.find(";") + 1].lstrip("RLAPI ")
    return "-1"

def rl_parse(path: str = ""):
    if not path:
        path = "raylib.h"
    rl_sheet = str()
    with open(path, "r") as raylib_h:
        for line in raylib_h.readlines():
            result = check_pattern(line)
            if result != "-1":
                rl_sheet += ("\t" + result + "\n")
        with open("raylib.lua", "w") as rl_lua:
            rl_lua.write("-- This file was auto-generated by Sunrayz.\n")
            rl_lua.write("-- Change anything only if you know what you're doing.\n\n")
            rl_lua.write("local ffi = require(\"ffi\")\n\n")
            rl_lua.write("ffi.cdef[[\n")
            rl_lua.write(rl_sheet)
            rl_lua.write("]]\n\nreturn ffi.C")

rl_parse("raylib.h")