import os


in_struct = False
in_enum = False
in_comment = False


banned_types = [
    "Camera3D",
    "Camera",
    "Mesh",
    "Transform",
    "ModelAnimPose",
    "BoneInfo",
    "Model",
    "ModelAnimation",
    "Ray",
    "RayCollision",
    "BoundingBox",
    "VrDeviceInfo",
    "VrStereoConfig"
]
banned_functions = [
    "LoadModel",
    "LoadModelFromMesh",
    "IsModelValid",
    "UnloadModel",
    "GetModelBoundingBox",
    "DrawModel",
    "DrawModelEx",
    "DrawModelWires",
    "DrawModelWiresEx",
    "DrawBoundingBox",
    "DrawBillboard",
    "DrawBillboardRec",
    "DrawBillboardPro",
    "UploadMesh",
    "UpdateMeshBuffer",
    "UnloadMesh",
    "DrawMesh",
    "DrawMeshInstanced",
    "GetMeshBoundingBox",
    "GenMeshTangents",
    "ExportMesh",
    "ExportMeshAsCode",
    "GenMeshPoly",
    "GenMeshPlane",
    "GenMeshCube",
    "GenMeshSphere",
    "GenMeshHemiSphere",
    "GenMeshCylinder",
    "GenMeshCone",
    "GenMeshTorus",
    "GenMeshKnot",
    "GenMeshHeightmap",
    "GenMeshCubicmap",
    "LoadMaterials",
    "LoadMaterialDefault",
    "IsMaterialValid",
    "UnloadMaterial",
    "SetMaterialTexture",
    "SetModelMeshMaterial",
    "LoadModelAnimations",
    "UpdateModelAnimation",
    "UpdateModelAnimationEx",
    "UnloadModelAnimations",
    "IsModelAnimationValid",
    "CheckCollisionSpheres",
    "CheckCollisionBoxes",
    "CheckCollisionBoxSphere",
    "GetRayCollisionSphere",
    "GetRayCollisionBox",
    "GetRayCollisionMesh",
    "GetRayCollisionTriangle",
    "GetRayCollisionQuad",
    "BeginVrStereoMode",
    "EndVrStereoMode",
    "LoadVrStereoConfig",
    "UnloadVrStereoConfig"
]


def check_pattern(line: str) -> str:
    global in_struct
    global in_enum
    global in_comment
    if in_comment:
        if line.rstrip().endswith("*/"):
            in_comment = False
        return "-1"
    if line.startswith("/*"):
        in_comment = True
        return "-1"
    if in_struct:
        if line.startswith(r"}"):
            in_struct = False
            return "RAYTYPE " + line[:line.find(";") + 1]
        return line[:line.find(";") + 1]
    elif in_enum:
        if line.startswith(r"}"):
            in_enum = False
            return line[:line.find(";") + 1]
        elif "," in line and line.find(",") < line.find("//"):
            return line[:line.find(",") + 1]
        elif "= " in line:
            return line[:line.find(" ", line.find("= ") + 2)]
        elif line.strip().startswith("//"):
            return "-1"
        else:
            for i in range(len(line)):
                if line[i] != " ":
                    return line[:line.find(" ", i)]
    if line.startswith("typedef"):
        if r"{" in line:
            if line.split(" ")[1] == "struct":
                in_struct = True
            elif line.split(" ")[1] == "enum":
                in_enum = True
            if r"}" not in line:
                return line[:line.find(r"{") + 1]
            else:
                in_struct = False
                in_enum = False
        return line[:line.find(";") + 1]
    elif line.startswith("RLAPI"):
        return line[len("RLAPI "):line.find(";") + 1]
    elif line.startswith("RAYGUIAPI"):
        return line[len("RAYGUIAPI "):line.find(";") + 1]
    return "-1"


def rl_parse(paths: list[str]) -> None:
    rl_sheet = str()
    rl_types = str()
    ready = False
    for path in paths:
        file_name = path.split(os.path.sep)[-1].split(".")[0]
        rl_sheet += f"\n\t// {file_name}.h\n\n"
        rl_types_buffer = str()
        rl_sheet_buffer = str()
        with open(path, "r") as raylib_h:
            for line in raylib_h.readlines():
                result = check_pattern(line)
                if result != "-1":
                    if result.startswith("RAYTYPE"):
                        type_name = result[len("RAYTYPE }"):result.find(";")].strip()
                        rl_types_buffer += f"\t\t{type_name.lower()} = ffi.metatype(\"{type_name}" + r'", {}),' + "\n"
                        rl_sheet_buffer += ("\t" + result[len("RAYTYPE "):] + "\n")
                        ready = True
                    else:
                        rl_sheet_buffer += ("\t" + result + "\n")
                        if not in_struct and not in_enum:
                            ready = True
                if ready:
                    for type in banned_types:
                        if f"}} {type};" not in rl_sheet_buffer:
                            rl_types += rl_types_buffer
                            rl_sheet += rl_sheet_buffer
                        rl_types_buffer = ""
                        rl_sheet_buffer = ""
                    ready = False
    with open(f"raylib.lua", "w") as lua_file:
        lua_file.write("-- This file was auto-generated by Sunrayz.\n")
        lua_file.write("-- Change anything only if you know what you're doing.\n\n")
        lua_file.write("local ffi = require(\"ffi\")\n\n")
        lua_file.write("ffi.cdef[[\n")
        lua_file.write(rl_sheet)
        lua_file.write("]]\n\nreturn {\n")
        lua_file.write("\tapi = ffi.load(\"raylib\"),\n")
        lua_file.write("\ttypes = {\n")
        lua_file.write(rl_types)
        lua_file.write("\t}\n")
        lua_file.write("}\n")
