import os


in_struct = False
in_enum = False


def check_pattern(line: str) -> str:
    global in_struct
    global in_enum
    if in_struct:
        if line.startswith(r"}"):
            in_struct = False
        return line[:line.find(";") + 1]
    elif in_enum:
        if line.startswith(r"}"):
            in_enum = False
            return line[:line.find(";") + 1]
        elif "," in line and line.find(",") < line.find("//"):
            return line[:line.find(",") + 1]
        elif "= " in line:
            return line[:line.find(" ", line.find("= ") + 2)]
        elif line.strip().startswith("//"):
            return "-1"
        else:
            for i in range(len(line)):
                if line[i] != " ":
                    return line[:line.find(" ", i)]
    if line.startswith("typedef"):
        if r"{" in line:
            if line.split(" ")[1] == "struct":
                in_struct = True
            elif line.split(" ")[1] == "enum":
                in_enum = True
            if r"}" not in line:
                return line[:line.find(r"{") + 1]
            else:
                in_struct = False
                in_enum = False
        return line[:line.find(";") + 1]
    elif line.startswith("RLAPI"):
        return line[len("RLAPI "):line.find(";") + 1]
    elif line.startswith("RAYGUIAPI"):
        return line[len("RAYGUIAPI "):line.find(";") + 1]
    return "-1"


def rl_parse(path: str = "") -> None:
    if not path:
        path = "raylib.h"
    rl_sheet = str()
    file_name = path.split(os.path.sep)[-1].split(".")[0]
    with open(path, "r") as raylib_h:
        for line in raylib_h.readlines():
            result = check_pattern(line)
            if result != "-1":
                rl_sheet += ("\t" + result + "\n")
        with open(f"{file_name}.lua", "w") as lua_file:
            lua_file.write("-- This file was auto-generated by Sunrayz.\n")
            lua_file.write("-- Change anything only if you know what you're doing.\n\n")
            lua_file.write("local ffi = require(\"ffi\")\n\n")
            lua_file.write("ffi.cdef[[\n")
            lua_file.write(rl_sheet)
            lua_file.write("]]\n\n")
            if file_name == "raylib":
                lua_file.write("local C = ffi.load(\"raylib\")\n\n")
                lua_file.write("return C\n")
            elif file_name == "raygui":
                lua_file.write("return ffi.C")
